type InboundIdentity = {
  airport: 'VTBD' | 'VTBS'
  callsign: string
  key: string
}

const MONITORED_MEMORY_MS = 6 * 60 * 60 * 1000
const SCAN_INTERVAL_MS = 500

function rowIdentity(row: HTMLElement): InboundIdentity | null {
  const airportCode = row.querySelector<HTMLElement>('.apt')?.textContent?.trim().toUpperCase()
  const airport = airportCode === 'BD' ? 'VTBD' : airportCode === 'BS' ? 'VTBS' : null
  const callsign = row.querySelector<HTMLElement>('.aman-inbound-acid strong')?.textContent?.trim().toUpperCase() || ''
  return airport && callsign ? { airport, callsign, key: `${airport}:${callsign}` } : null
}

function findInboundRow(key: string) {
  return Array.from(document.querySelectorAll<HTMLElement>('.aman-inbound-row')).find((row) => rowIdentity(row)?.key === key) ?? null
}

/**
 * Flights already visible as MON outside the 300 NM processing boundary are expected
 * traffic, not late inserts. When one of those known flights crosses the boundary,
 * automatically accept the transient LATE state generated by the legacy React guard.
 *
 * A genuinely new flight that first appears already inside the boundary is left as
 * INSERT so the controller still explicitly accepts disruptive late-connect traffic.
 */
export function installKnownInboundAdmissionRuntime() {
  const monitoredAt = new Map<string, number>()
  let scheduled = false
  let disposed = false

  const scan = () => {
    if (disposed) return
    const now = Date.now()

    document.querySelectorAll<HTMLElement>('.aman-inbound-row').forEach((row) => {
      const identity = rowIdentity(row)
      if (!identity) return

      const planningState = String(row.dataset.planningState || '').trim().toUpperCase()
      if (planningState === 'MONITORED') {
        monitoredAt.set(identity.key, now)
        delete row.dataset.autoBoundaryAdmission
        return
      }

      if (planningState !== 'LATE' || !monitoredAt.has(identity.key)) return
      if (row.dataset.autoBoundaryAdmission === 'pending') return

      const insertButton = row.querySelector<HTMLButtonElement>('.aman-late-insert-button')
      if (!insertButton) return

      row.dataset.autoBoundaryAdmission = 'pending'
      window.requestAnimationFrame(() => {
        if (disposed) return
        const currentRow = findInboundRow(identity.key)
        const currentButton = currentRow?.querySelector<HTMLButtonElement>('.aman-late-insert-button')
        if (currentRow?.dataset.planningState === 'LATE' && currentButton && !currentButton.disabled) {
          currentButton.click()
        }
        monitoredAt.delete(identity.key)
        if (currentRow) delete currentRow.dataset.autoBoundaryAdmission
      })
    })

    for (const [key, seenAt] of monitoredAt) {
      if (now - seenAt > MONITORED_MEMORY_MS) monitoredAt.delete(key)
    }
  }

  const scheduleScan = () => {
    if (disposed || scheduled) return
    scheduled = true
    window.requestAnimationFrame(() => {
      scheduled = false
      scan()
    })
  }

  const observer = new MutationObserver(scheduleScan)
  observer.observe(document.body, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: ['data-planning-state'],
  })

  scan()
  const timer = window.setInterval(scan, SCAN_INTERVAL_MS)

  return () => {
    disposed = true
    observer.disconnect()
    window.clearInterval(timer)
    monitoredAt.clear()
  }
}
