-- Staff-managed AIRAC / Little Navmap navdata staging for the AMAN project.
-- Raw SQLite packages are never stored in Supabase. The staff browser extracts only
-- the VTBD/VTBS procedure records needed by the AMAN and sends structured rows here.

create table if not exists public.navdata_cycles (
  id uuid primary key default gen_random_uuid(),
  cycle text not null,
  valid_through text,
  source_kind text not null default 'LITTLE_NAVMAP_NAVIGRAPH',
  source_filename text not null,
  source_sha256 text not null unique,
  source_file_size bigint,
  source_db_version_major integer,
  source_db_version_minor integer,
  source_data_source text,
  status text not null default 'STAGED' check (status in ('STAGED', 'ACTIVE', 'ARCHIVED')),
  procedure_count integer not null default 0,
  transition_count integer not null default 0,
  leg_count integer not null default 0,
  constraint_leg_count integer not null default 0,
  imported_at timestamptz not null default now(),
  imported_by_vid text not null,
  imported_by_name text,
  activated_at timestamptz,
  activated_by_vid text,
  activated_by_name text,
  archived_at timestamptz,
  notes text
);

create unique index if not exists navdata_cycles_one_active_idx
  on public.navdata_cycles ((status)) where status = 'ACTIVE';
create index if not exists navdata_cycles_cycle_idx on public.navdata_cycles (cycle);
create index if not exists navdata_cycles_imported_idx on public.navdata_cycles (imported_at desc);

create table if not exists public.navdata_procedures (
  id bigint generated by default as identity primary key,
  cycle_id uuid not null references public.navdata_cycles(id) on delete cascade,
  airport text not null check (airport in ('VTBD', 'VTBS')),
  source_approach_id bigint not null,
  designator text not null,
  runway_name text,
  arinc_name text,
  source_type text,
  source_suffix text,
  aircraft_category text,
  fingerprint text not null,
  common_leg_count integer not null default 0,
  transition_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique (cycle_id, source_approach_id)
);

create index if not exists navdata_procedures_cycle_airport_idx
  on public.navdata_procedures (cycle_id, airport, designator);
create index if not exists navdata_procedures_lookup_idx
  on public.navdata_procedures (airport, designator, runway_name);

create table if not exists public.navdata_transitions (
  id bigint generated by default as identity primary key,
  cycle_id uuid not null references public.navdata_cycles(id) on delete cascade,
  procedure_id bigint not null references public.navdata_procedures(id) on delete cascade,
  source_transition_id bigint not null,
  ident text,
  source_type text,
  aircraft_category text,
  leg_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique (cycle_id, source_transition_id)
);

create index if not exists navdata_transitions_procedure_idx
  on public.navdata_transitions (procedure_id, ident);

create table if not exists public.navdata_procedure_legs (
  id bigint generated by default as identity primary key,
  cycle_id uuid not null references public.navdata_cycles(id) on delete cascade,
  procedure_id bigint not null references public.navdata_procedures(id) on delete cascade,
  transition_id bigint references public.navdata_transitions(id) on delete cascade,
  leg_kind text not null check (leg_kind in ('COMMON', 'TRANSITION')),
  leg_order integer not null,
  source_leg_id bigint not null,
  path_terminator text,
  arinc_descr_code text,
  approach_fix_type text,
  turn_direction text,
  rnp double precision,
  fix_type text,
  fix_ident text,
  fix_region text,
  fix_airport_ident text,
  fix_lon double precision,
  fix_lat double precision,
  recommended_fix_type text,
  recommended_fix_ident text,
  recommended_fix_region text,
  recommended_fix_lon double precision,
  recommended_fix_lat double precision,
  is_flyover boolean not null default false,
  is_true_course boolean not null default false,
  course double precision,
  distance_nm double precision,
  leg_time_minutes double precision,
  theta double precision,
  rho double precision,
  alt_descriptor text,
  altitude1_ft double precision,
  altitude2_ft double precision,
  speed_limit_type text,
  speed_limit_kt integer,
  vertical_angle double precision,
  created_at timestamptz not null default now(),
  unique (cycle_id, leg_kind, source_leg_id)
);

create index if not exists navdata_legs_procedure_idx
  on public.navdata_procedure_legs (procedure_id, transition_id, leg_order);
create index if not exists navdata_legs_fix_idx
  on public.navdata_procedure_legs (fix_ident);

create table if not exists public.navdata_events (
  id bigint generated by default as identity primary key,
  cycle_id uuid references public.navdata_cycles(id) on delete set null,
  cycle text not null,
  action text not null,
  actor_vid text not null,
  actor_name text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists navdata_events_created_idx on public.navdata_events (created_at desc);

alter table public.navdata_cycles enable row level security;
alter table public.navdata_procedures enable row level security;
alter table public.navdata_transitions enable row level security;
alter table public.navdata_procedure_legs enable row level security;
alter table public.navdata_events enable row level security;

create or replace function public.activate_navdata_cycle(
  p_cycle_id uuid,
  p_vid text,
  p_name text
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.navdata_cycles%rowtype;
begin
  select * into target from public.navdata_cycles where id = p_cycle_id for update;
  if not found then
    raise exception 'Navdata cycle not found';
  end if;

  if target.status not in ('STAGED', 'ARCHIVED', 'ACTIVE') then
    raise exception 'Navdata cycle cannot be activated from status %', target.status;
  end if;

  update public.navdata_cycles
     set status = 'ARCHIVED', archived_at = now()
   where status = 'ACTIVE' and id <> p_cycle_id;

  update public.navdata_cycles
     set status = 'ACTIVE',
         activated_at = now(),
         activated_by_vid = p_vid,
         activated_by_name = p_name,
         archived_at = null
   where id = p_cycle_id;

  insert into public.navdata_events (cycle_id, cycle, action, actor_vid, actor_name, details)
  values (p_cycle_id, target.cycle, 'ACTIVATE', p_vid, p_name, jsonb_build_object('source_sha256', target.source_sha256));
end;
$$;

revoke all on function public.activate_navdata_cycle(uuid, text, text) from public;
