create table if not exists public.airports (
  id uuid primary key default gen_random_uuid(),
  icao text not null unique,
  name text not null,
  city text,
  fir text not null default 'BANGKOK',
  active boolean not null default true,
  archived_at timestamptz,
  created_by_vid text,
  created_by_name text,
  updated_by_vid text,
  updated_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.runway_configs (
  id uuid primary key default gen_random_uuid(),
  airport_id uuid not null references public.airports(id) on delete restrict,
  flow text not null,
  label text not null,
  timing_status text not null default 'PENDING' check (timing_status in ('ACTIVE','PENDING','DISABLED')),
  active boolean not null default true,
  sort_order integer not null default 0,
  notes text,
  created_by_vid text,
  created_by_name text,
  updated_by_vid text,
  updated_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (airport_id, flow)
);

create table if not exists public.star_procedures (
  id uuid primary key default gen_random_uuid(),
  runway_config_id uuid not null references public.runway_configs(id) on delete restrict,
  designator text not null,
  entry_fix text,
  runway_applicability text,
  chart_reference text,
  source text,
  effective_from date,
  effective_to date,
  active boolean not null default true,
  created_by_vid text,
  created_by_name text,
  updated_by_vid text,
  updated_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (runway_config_id, designator, effective_from)
);

create table if not exists public.config_history (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('AIRPORT','RUNWAY_CONFIG','STAR_PROCEDURE','FIX_TIMING')),
  entity_id text not null,
  action text not null check (action in ('INSERT','UPDATE','ARCHIVE','RESTORE')),
  old_row jsonb,
  new_row jsonb,
  changed_by_vid text,
  changed_by_name text,
  reason text,
  changed_at timestamptz not null default now()
);

create index if not exists config_history_entity_idx on public.config_history(entity_type, entity_id, changed_at desc);
create index if not exists config_history_changed_at_idx on public.config_history(changed_at desc);
create index if not exists runway_configs_airport_idx on public.runway_configs(airport_id, sort_order, flow);
create index if not exists star_procedures_runway_idx on public.star_procedures(runway_config_id, active, designator);

create or replace function public.set_master_updated_at()
returns trigger
language plpgsql
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create or replace function public.audit_master_config()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
declare
  entity text;
  actor_vid text;
  actor_name text;
  effective_action text;
begin
  entity := case tg_table_name
    when 'airports' then 'AIRPORT'
    when 'runway_configs' then 'RUNWAY_CONFIG'
    when 'star_procedures' then 'STAR_PROCEDURE'
    else upper(tg_table_name)
  end;

  if tg_op = 'INSERT' then
    actor_vid := coalesce(new.created_by_vid, new.updated_by_vid);
    actor_name := coalesce(new.created_by_name, new.updated_by_name);
    insert into public.config_history(entity_type, entity_id, action, new_row, changed_by_vid, changed_by_name)
    values (entity, new.id::text, 'INSERT', to_jsonb(new), actor_vid, actor_name);
    return new;
  end if;

  actor_vid := new.updated_by_vid;
  actor_name := new.updated_by_name;
  effective_action := 'UPDATE';

  if old.active = true and new.active = false then
    effective_action := 'ARCHIVE';
  elsif old.active = false and new.active = true then
    effective_action := 'RESTORE';
  end if;

  insert into public.config_history(entity_type, entity_id, action, old_row, new_row, changed_by_vid, changed_by_name)
  values (entity, new.id::text, effective_action, to_jsonb(old), to_jsonb(new), actor_vid, actor_name);
  return new;
end;
$function$;

drop trigger if exists set_airports_updated_at on public.airports;
create trigger set_airports_updated_at before update on public.airports for each row execute function public.set_master_updated_at();
drop trigger if exists set_runway_configs_updated_at on public.runway_configs;
create trigger set_runway_configs_updated_at before update on public.runway_configs for each row execute function public.set_master_updated_at();
drop trigger if exists set_star_procedures_updated_at on public.star_procedures;
create trigger set_star_procedures_updated_at before update on public.star_procedures for each row execute function public.set_master_updated_at();

drop trigger if exists audit_airports_config on public.airports;
create trigger audit_airports_config after insert or update on public.airports for each row execute function public.audit_master_config();
drop trigger if exists audit_runway_configs_config on public.runway_configs;
create trigger audit_runway_configs_config after insert or update on public.runway_configs for each row execute function public.audit_master_config();
drop trigger if exists audit_star_procedures_config on public.star_procedures;
create trigger audit_star_procedures_config after insert or update on public.star_procedures for each row execute function public.audit_master_config();

alter table public.airports enable row level security;
alter table public.runway_configs enable row level security;
alter table public.star_procedures enable row level security;
alter table public.config_history enable row level security;

insert into public.airports (icao, name, city, fir, active)
values
  ('VTBD', 'Don Mueang International Airport', 'Bangkok', 'BANGKOK', true),
  ('VTBS', 'Suvarnabhumi Airport', 'Bangkok', 'BANGKOK', false)
on conflict (icao) do nothing;

insert into public.runway_configs (airport_id, flow, label, timing_status, active, sort_order)
select a.id, x.flow, x.label, x.timing_status, x.active, x.sort_order
from public.airports a
join (values
  ('VTBD','21','21L / 21R','ACTIVE',true,10),
  ('VTBD','03','03L / 03R','PENDING',true,20),
  ('VTBS','01_02','01 / 02L / 02R','PENDING',false,10),
  ('VTBS','19_20','19 / 20L / 20R','PENDING',false,20)
) as x(icao,flow,label,timing_status,active,sort_order) on x.icao = a.icao
on conflict (airport_id, flow) do nothing;
